# Generated by Django 3.1.2 on 2020-10-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ProfileId', models.AutoField(primary_key=True, serialize=False)),
                ('Position', models.CharField(max_length=100)),
                ('AboutYourSelf', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('BirthPlace', models.CharField(max_length=100)),
                ('PersonAdd', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('BirthDate', models.DateField()),
                ('BobileNumber', models.CharField(max_length=100)),
                ('EmailAdd', models.CharField(max_length=100)),
                ('ProSkills', models.CharField(max_length=100)),
                ('Elementary', models.CharField(max_length=100)),
                ('YearElemFrom', models.CharField(max_length=100)),
                ('YearElemTo', models.CharField(max_length=100)),
                ('AddressElem', models.CharField(max_length=100)),
                ('Secondary', models.CharField(max_length=100)),
                ('YearSecFrom', models.CharField(max_length=100)),
                ('YearSecTo', models.CharField(max_length=100)),
                ('AddressSec', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=100)),
                ('YearColFrom', models.CharField(max_length=100)),
                ('YearColTo', models.CharField(max_length=100)),
                ('AddressCollege', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('YearFromA', models.CharField(max_length=100)),
                ('YearToA', models.CharField(max_length=100)),
                ('AddressA', models.CharField(max_length=100)),
                ('DutiesA', models.CharField(max_length=100)),
                ('CompanyB', models.CharField(max_length=100)),
                ('YearFromB', models.CharField(max_length=100)),
                ('YearToB', models.CharField(max_length=100)),
                ('AddressB', models.CharField(max_length=100)),
                ('DutiesB', models.CharField(max_length=100)),
                ('CompanyC', models.CharField(max_length=100)),
                ('YearFromC', models.CharField(max_length=100)),
                ('YearToC', models.CharField(max_length=100)),
                ('AddressC', models.CharField(max_length=100)),
                ('DutiesC', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfResume',
            fields=[
                ('ResumeId', models.AutoField(primary_key=True, serialize=False)),
                ('ResumeName', models.CharField(max_length=100)),
            ],
        ),
    ]
